### ISSUE TITLE
-n does not seem to be honored

### ISSUE THREAD

**Issue by wasade** [biocore/unifrac-binaries#17]
I'm running `ssu ... -n 8` however, it appears that `ssu` is using 16 threads

**Comment by sfiligoi** [comment]
Yes, the semantics of -n has changed.
The documentation has unfortunately not been updated :(

-n now stands for "split the problem in N subproblems to be run in sequence", with the reasoning being that we use less memory during Unifrac compute. This is especially useful for GPU compute.
While it limits the amount of memory saving during the IO phase, it is still beneficial.

The number of threads is fully controlled by the OpenMP threading library, i.e. OMP_NUM_THREADS.

**Comment by wasade** [comment]
I think we should correctly support the threads parameters from the python interface. Would it suffice to use Python to set OMP_NUM_THREADS?

W/ documentation, I think we should update the ssu usage string to reflect what -n does, I think a new parameter name probably makes sense, and to also note specifically in the usage string the use of OMP_NUM_THREADS

**Comment by wasade** [comment]
I know

**Comment by sfiligoi** [comment]
Let's deprecate -n and document it accordingly.
I will add a separate flag for the problem splitting.

**Comment by wasade** [comment]
Thanks!

**Comment by sfiligoi** [comment]
Released in 1.2.
