### ISSUE TITLE
Division by zero causes a test failure in unifrac

### ISSUE THREAD

**Issue by vpa1977** [biocore/unifrac-binaries#51]
```
=====================================================================
FAIL: test_faith_pd_none_observed (unifrac.tests.test_api.FaithPDEdgeCasesTests.test_faith_pd_none_observed)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_unifrac/build/unifrac/tests/test_api.py", line 718, in test_faith_pd_none_observed
    self.assertAlmostEqual(actual[0], expected)
AssertionError: 6.25 != 0.0 within 7 places (6.25 difference)
```
This is due `void su::set_proportions()` dividing props[i] by sample_count[i] which is 0. 

In order to avoid undefined behaviour the value of props[i] can by adjusted to std::numeric_limits<double>::max()/lowest()

**Comment by wasade** [comment]
Does this exist with the latest version?

**Comment by vpa1977** [comment]
yes it does

**Comment by vpa1977** [comment]
I think it is due to some dependency - in `void biom_inmem::compute_sample_counts() ` n_samples is 1, but  `resident_obj.obs_counts_resident[i];` is 0, which leaves the sample_count[0] as 0.

**Comment by sfiligoi** [comment]
@vpa1977 I need a way to reproduce this.
I just re-installed the latest unifrac (as per CI), and it passes all tests with flying colors.

The most likely explanation is that something in your setup is picking up something it should not.
But I cannot help unless I can reproduce.

**Comment by vpa1977** [comment]
Yes, it is a bit flaky, due to the UB, so it might pass in some cases[1]. 

[1] https://github.com/biocore/unifrac-binaries/pull/52#issuecomment-1749824583
